### ISSUE TITLE
Neganari faction

### ISSUE THREAD

**Issue by Nsyion** [GreyCardinal69/EOPR-Collection#4]
Artemis and Zeus have the same icon in top right corner of screen making differentiating between them inconvenient.

**Comment by GreyCardinal69** [comment]
I checked db, icon seem to be correctly assigned?

**Comment by Nsyion** [comment]
![image](https://github.com/GreyCardinal69/EOPR-Collection/assets/60604396/25a21d6e-1035-45f0-9de4-84d1495f2e51) 
![image](https://github.com/GreyCardinal69/EOPR-Collection/assets/60604396/79574d80-a9ff-4bd5-8a0a-dc5516c87ac3)
