### ISSUE TITLE
Daazen faction

### ISSUE THREAD

**Issue by Nsyion** [GreyCardinal69/EOPR-Collection#5]
Nosferatu has laughably poor dps, presumably something overlooked with healing changes. Additionally, if tractor beam connects with player cloak can't escape it. 

Vampiric weapons seem to be too-weak from testing and displayed stats. 
Heavy Fusion Beam has significantly worse efficiency than normal variant.

**Comment by GreyCardinal69** [comment]
Daazen weps got rebalanced, nosferatu buffed.
